# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'treasure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for treasure
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire', '~> 5.2'
  pod 'GoogleMaps'
  pod 'GoogleSignIn'
end
